# Generated by Django 3.2.7 on 2021-09-29 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Watchlist', '0002_auto_20210929_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='platform',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to='Watchlist.streamon'),
            preserve_default=False,
        ),
    ]
