# Generated by Django 3.2.7 on 2021-10-04 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Watchlist', '0005_review_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='number_rating',
            field=models.IntegerField(default=0),
        ),
    ]
